from __future__ import annotations

from typing import Any, Protocol
from mcp.types import CallToolResult


class AEMProvider(Protocol):
    async def get_page_properties(self, path: str) -> dict[str, Any]: ...
    async def list_child_pages(self, root: str, limit: int = 50) -> dict[str, Any]: ...
    async def find_component_usage(self, root: str, resource_type: str, limit: int = 50) -> dict[str, Any]: ...
    async def list_components(self, page_path: str, max_depth: int = 10, limit: int = 200) -> dict[str, Any]: ...
    async def get_component_properties(self, component_path: str) -> dict[str, Any]: ...
    async def get_component_authoring_schema(self, resource_type: str) -> dict[str, Any]: ...
    async def list_allowed_components(self, container_path: str, limit: int = 200) -> dict[str, Any]: ...
    async def search_assets(self, root: str = "/content/dam", text: str | None = None, mime_type: str | None = None, limit: int = 50, offset: int = 0) -> dict[str, Any]: ...
    async def get_asset_metadata(self, asset_path: str) -> dict[str, Any]: ...
    async def get_asset_preview(self, asset_path: str, rendition: str | None = None, max_bytes: int | None = None) -> CallToolResult: ...
